<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a0e726573706f6e73652e70726f746f120e4d794170702e4d6573" .
            "73616765731a0a757365722e70726f746f2291010a08526573706f6e7365" .
            "122f0a056572726f7218012001280b321e2e4d794170702e4d6573736167" .
            "65732e526573706f6e73652e4572726f72480012240a0475736572180220" .
            "01280b32142e4d794170702e4d657373616765732e5573657248001a260a" .
            "054572726f72120c0a04636f6465180120012805120f0a076d6573736167" .
            "6518022001280942060a0464617461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

