<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace MyApp\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>MyApp.Messages.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    protected $data;

    public function __construct() {
        \GPBMetadata\Request::initOnce();
        parent::__construct();
    }

    /**
     * <code>.MyApp.Messages.User user = 1;</code>
     */
    public function getUser()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.MyApp.Messages.User user = 1;</code>
     */
    public function setUser(&$var)
    {
        GPBUtil::checkMessage($var, \MyApp\Messages\User::class);
        $this->writeOneof(1, $var);
    }

    public function getData()
    {
        return $this->data;
    }

}

