<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace MyApp\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>MyApp.Messages.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    protected $data;

    public function __construct() {
        \GPBMetadata\Response::initOnce();
        parent::__construct();
    }

    /**
     * <code>.MyApp.Messages.Response.Error error = 1;</code>
     */
    public function getError()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.MyApp.Messages.Response.Error error = 1;</code>
     */
    public function setError(&$var)
    {
        GPBUtil::checkMessage($var, \MyApp\Messages\Response_Error::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.MyApp.Messages.User user = 2;</code>
     */
    public function getUser()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.MyApp.Messages.User user = 2;</code>
     */
    public function setUser(&$var)
    {
        GPBUtil::checkMessage($var, \MyApp\Messages\User::class);
        $this->writeOneof(2, $var);
    }

    public function getData()
    {
        return $this->data;
    }

}

