<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace MyApp\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>MyApp.Messages.Response.Error</code>
 */
class Response_Error extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     * <code>string message = 2;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\Response::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <code>int32 code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;
    }

    /**
     * <code>string message = 2;</code>
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * <code>string message = 2;</code>
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

}

